### ISSUE TITLE
KruxInstaller.Setup.0.0.1-alpha-3 Windows Maix Dock M1 installer error

### ISSUE THREAD

**Issue by tadeubas** [selfcustody/krux-installer#4]
I've tested the installer for Windows `v0.0.1-alpha-3` and got some things to share:

1. It needs to **tell the user to click UNZIP** after downloading and checking signatures from Krux (I've clicked on BACK 🤦‍♂️ and later on I get an error)
2. When executing the program for the second time and selecting the Krux version, I think the **OK button should** be "proceed without download"
3. For **maixpy_dock** the **flash command** NEEDS to use the parameter `-B dan` instead of `-B goE`. Otherwise even with the board connected to the USB, it always gives an error (also the error accumulates on the terminal screen, but for me this is ok)

1)
![image](https://user-images.githubusercontent.com/5518496/215844845-94859019-8549-4b66-b4dd-e2691953c294.png)
![image](https://user-images.githubusercontent.com/5518496/215845145-08bbcba7-344b-4641-98a2-643beb9abf90.png)

2)
![image](https://user-images.githubusercontent.com/5518496/215846484-972d544e-f65b-43bd-a738-5b5cd30062bc.png)

3)
![image](https://user-images.githubusercontent.com/5518496/215847529-6377a6bc-b811-4736-861f-aa41734993e5.png)

**Comment by qlrd** [comment]
So there's 3 problems, 2 of them as UX and one is, effectively, a bug, correct?

1. I will add this to the branch I'm [working on](https://github.com/qlrd/krux-installer/tree/linux-appimage-wdio);
2. In the above [branch](https://github.com/qlrd/krux-installer/tree/linux-appimage-wdio), I changed the `OK` and `Cancel` buttons to `Download` and `Proceed`. You believe that `OK` (for not download) and `Download` will be better?
3. Bug:
  * About the command change from `-B goE` to `-B dan` I will add this as fast as I can;
  * I will work to remove these accumulation (it's a Vue persistent data question);

**Comment by tadeubas** [comment]
Correct!

1. Ok;
2. I would place the `Proceed` first and `Download the file again` later;
3. - Yes, it is just that simple parameter change, you can see it on krux code [here](https://github.com/selfcustody/krux/blob/main/krux#L91).
   - IMHO you don't need to remove these accumulation, but do as you wish 😄.

**Comment by qlrd** [comment]
2. " place the Proceed first and Download the file again later " fixed on branch `linux-appimage-wdio`.

Example:
![Screenshot_20230131_203409](https://user-images.githubusercontent.com/106913782/215908024-753d38f9-4d92-430d-8996-8f04f9ded624.png)

Check the commit [8acade0](https://github.com/qlrd/krux-installer/commit/8acade0d1162b9ef6aa805163a370b82aa503b94) and its [e2e test](https://github.com/qlrd/krux-installer/actions/runs/4059221895/jobs/6987036330) to verify.

Once i finish all tests on linux, i will test them on windows (an maybe a virtualized mac on github).

**Comment by qlrd** [comment]
1. Created a warning message from your request;

I don't know if this positioning of the message on the left side and buttons on the right side is adequate. What do you think?
![Screenshot_20230203_201516](https://user-images.githubusercontent.com/106913782/216729165-4f7a676e-14cf-476b-b064-f5afcc1ea90c.png)

**Comment by tadeubas** [comment]
I think it is awesome, the text on left aligned with the buttons on the right makes the user read and understand what to do next... I would only change "You will need to unzip this release before flash" to "You need to UNZIP this release before flash" just to make sure the user follow the correct path.

One question I have is the case of the signature verification fail... maybe hide the Unzip button? Or place another text in saying something in the WARN:?

**Comment by qlrd** [comment]
Sorry for late response;

> One question I have is the case of the signature verification fail... 

If signature verification response fail, the user will receive an "alert" message and the page goes to main page; then you can download again the release.

**Comment by qlrd** [comment]
Fixed on  [4996231](https://github.com/selfcustody/krux-installer/commit/49962314074aecaaaa951c40d73f3d8491381c7a) and [1a7c6ba](https://github.com/selfcustody/krux-installer/commit/1a7c6bac7379a706f816738e03a1e1573f3eabf0)
