### ISSUE TITLE
[Proposta] Adição de navegação contínua do cursor

### ISSUE THREAD

**Issue by BitcoinMaranhao** [selfcustody/krux-installer#51]
adicionar comando de navegação contínua não só reduzirá o tempo de digitação no teclado como aumentará também o tempo de vida dos botões dos dispositivos.

**Comment by tadeubas** [comment]
Hey @BitcoinMaranhao this is just about the Krux Installer project. The correct project for the Krux devices is here:
https://github.com/selfcustody/krux/issues

**Comment by qlrd** [comment]
Since it isnt related, i will close
